PROVIDER_SCHEMAS = {
    "spotify": {
        "display_name": "Spotify",
        "category": "Music",
        "icon": "spotify",
        "description": "Connect Spotify for the full HomeHub music player, library, podcasts, search and Spotify Connect playback.",
        "what_it_does": [
            "Adds the full Spotify player, search, playlists, saved podcasts/episodes and personalised library views.",
            "Lets HomeHub transfer and control playback on available Spotify Connect targets, including matched HomeHub speakers.",
            "Does not discover speakers by itself; Sonos/Google/Alexa are discovered separately.",
        ],
        "setup_steps": [
            "Create a Spotify developer application and copy its Client ID and Client secret.",
            "Add the Redirect URI shown below to the Spotify app exactly as displayed.",
            "Save the credentials here, then authorise HomeHub in the Spotify window.",
            "Approve the requested library and playback permissions. Existing HomeHub Spotify users may need to authorise once more after player upgrades.",
            "Return to this page and verify the connection, then open Spotify from the main sidebar.",
        ],
        "notes": [
            "Spotify playback requires a Spotify account and a target that is available through Spotify Connect.",
        ],
        "supports_device_discovery": False,
        "fields": [
            {
                "name": "client_id",
                "label": "Client ID",
                "type": "string",
                "secret": True,
                "description": "From your Spotify developer application.",
            },
            {
                "name": "client_secret",
                "label": "Client secret",
                "type": "password",
                "secret": True,
                "description": "Stored encrypted by HomeHub.",
            },
            {
                "name": "redirect_uri",
                "label": "Redirect URI",
                "type": "string",
                "default": "http://localhost:8000/api/v1/integration-accounts/spotify-callback/",
                "description": "This exact URI must also be configured in your Spotify developer app.",
            },
        ],
        "auth_type": "oauth",
    },
    "irobot": {
        "display_name": "iRobot",
        "category": "Robot vacuums",
        "icon": "vacuum",
        "description": "Connect your iRobot account for cloud-backed live location data on newer Roomba firmware.",
        "what_it_does": [
            "Authenticates HomeHub to the same iRobot account used by the mobile app.",
            "Provides the live-map position stream used by newer SMART-tier Roombas that no longer publish pose coordinates over local MQTT.",
            "Keeps normal Roomba controls and state retrieval local; the cloud account is only used where the local protocol no longer exposes the required data.",
        ],
        "setup_steps": [
            "Enter the email address and password used by the iRobot Home app.",
            "Keep the country code set to GB for a UK account.",
            "Click Test & connect. HomeHub will verify the account and confirm that it can see your robots.",
            "Existing Roombas configured with a BLID will automatically use this account for live floor-plan tracking when local pose data is unavailable.",
        ],
        "notes": [
            "Some recent Roomba firmware still supports local MQTT control but deliberately omits the old pose field. Live floor-plan movement then requires iRobot's cloud live-map stream.",
            "If iRobot reports that no MQTT slot is available, fully close the iRobot mobile app and retry.",
        ],
        "supports_device_discovery": False,
        "fields": [
            {
                "name": "username",
                "label": "iRobot email",
                "type": "string",
                "description": "The email address used by the iRobot Home app.",
            },
            {
                "name": "password",
                "label": "iRobot password",
                "type": "password",
                "secret": True,
                "description": "Stored encrypted by HomeHub.",
            },
            {
                "name": "country_code",
                "label": "Country code",
                "type": "string",
                "default": "GB",
                "description": "Two-letter iRobot account country code. UK accounts normally use GB.",
            },
        ],
        "auth_type": "credentials",
    },
    "hive": {
        "display_name": "Hive",
        "category": "Heating",
        "icon": "heating",
        "description": "Connect your Hive account so HomeHub can discover and control heating zones.",
        "what_it_does": [
            "Authenticates HomeHub to your Hive account.",
            "Discovers supported Hive heating zones/thermostats.",
            "Allows target temperature, mode and boost controls from HomeHub.",
        ],
        "setup_steps": [
            "Enter the same email address and password you use for Hive.",
            "Click Test & connect. HomeHub will perform a real Hive login.",
            "Once verified, HomeHub will check the account for controllable heating devices.",
            "Go to Devices to complete setup for any discovered Hive heating zones.",
        ],
        "notes": [
            "An integration account is not itself a thermostat. Connected means the account was verified; individual heating devices are added from Devices.",
        ],
        "supports_device_discovery": True,
        "fields": [
            {
                "name": "username",
                "label": "Hive email",
                "type": "string",
                "description": "The email address used to sign in to Hive.",
            },
            {
                "name": "password",
                "label": "Hive password",
                "type": "password",
                "secret": True,
                "description": "Stored encrypted by HomeHub.",
            },
        ],
        "auth_type": "credentials",
    },
    "ring": {
        "display_name": "Ring",
        "category": "Security",
        "icon": "doorbell",
        "description": "Connect Ring for doorbells and cameras.",
        "what_it_does": [
            "Discovers Ring cameras and doorbells attached to your account.",
            "Allows HomeHub to request camera snapshots and supported light/siren controls.",
            "Uses Ring account authentication and may require a one-time 2FA code.",
        ],
        "setup_steps": [
            "Enter your Ring email and password.",
            "If Ring requests 2FA, enter the fresh code and test the connection again.",
            "After verification HomeHub will discover supported Ring cameras/doorbells.",
            "Go to Devices to complete setup for the devices you want to use.",
        ],
        "notes": [
            "Ring may periodically require re-authentication.",
            "The Ring Python integration is based on reverse-engineered endpoints and may need maintenance when Ring changes its service.",
        ],
        "supports_device_discovery": True,
        "fields": [
            {"name": "username", "label": "Ring email", "type": "string"},
            {
                "name": "password",
                "label": "Ring password",
                "type": "password",
                "secret": True,
            },
            {
                "name": "otp",
                "label": "2FA code",
                "type": "string",
                "optional": True,
                "description": "Only needed when Ring asks for a fresh authentication code.",
            },
        ],
        "auth_type": "credentials_2fa",
    },
    "alexa": {
        "display_name": "Amazon Alexa",
        "category": "Speakers",
        "icon": "speaker",
        "description": "Connect an Amazon account so HomeHub can discover and control Echo/Alexa devices.",
        "what_it_does": [
            "Discovers Echo/Alexa speakers on the configured Amazon account.",
            "Provides playback, volume, announcement and text-to-speech controls where supported.",
            "Can optionally use Spotify through the separate Spotify integration.",
        ],
        "setup_steps": [
            "Enter the Amazon account used by your Echo devices.",
            "Keep the Alexa URL set to your regional Alexa endpoint unless you know you need a different one.",
            "If you use an authenticator secret, enter it so the Alexa library can satisfy supported 2FA flows.",
            "Test the connection, then go to Devices to add discovered Echo devices.",
        ],
        "notes": [
            "Alexa control uses an unofficial Amazon web API. Amazon changes can temporarily break the integration.",
        ],
        "supports_device_discovery": True,
        "fields": [
            {"name": "email", "label": "Amazon email", "type": "string"},
            {
                "name": "password",
                "label": "Amazon password",
                "type": "password",
                "secret": True,
            },
            {
                "name": "url",
                "label": "Amazon Alexa URL",
                "type": "string",
                "default": "https://alexa.amazon.co.uk",
                "description": "Regional Alexa endpoint; UK homes normally use the default.",
            },
            {
                "name": "otp_secret",
                "label": "Authenticator secret",
                "type": "password",
                "secret": True,
                "optional": True,
                "description": "Optional authenticator secret used by supported Alexa login flows.",
            },
        ],
        "auth_type": "credentials",
    },
    "ring_alarm_mqtt": {
        "display_name": "Ring Alarm MQTT",
        "category": "Security",
        "icon": "alarm",
        "description": "Connect HomeHub to a separately running Ring Alarm MQTT bridge.",
        "what_it_does": [
            "Connects to your MQTT broker and verifies broker authentication.",
            "Allows Ring Alarm panels exposed by your bridge to be armed/disarmed through HomeHub.",
            "This is a bridge integration; it is not the same as the Ring camera account above.",
        ],
        "setup_steps": [
            "Run/configure a compatible Ring-to-MQTT bridge on your network.",
            "Enter the MQTT broker hostname/IP and port.",
            "Add broker credentials if your MQTT server requires them.",
            "Test the broker connection, then manually add/configure the Ring Alarm panel using its MQTT topic.",
        ],
        "notes": [
            "HomeHub does not log into Ring Alarm directly here; the MQTT bridge is responsible for Ring connectivity.",
        ],
        "supports_device_discovery": False,
        "fields": [
            {
                "name": "broker",
                "label": "MQTT broker",
                "type": "string",
                "description": "Hostname or IP address of the MQTT broker used by your Ring bridge.",
            },
            {"name": "port", "label": "MQTT port", "type": "number", "default": 1883},
            {
                "name": "username",
                "label": "MQTT username",
                "type": "string",
                "optional": True,
            },
            {
                "name": "password",
                "label": "MQTT password",
                "type": "password",
                "secret": True,
                "optional": True,
            },
            {
                "name": "location_id",
                "label": "Ring location ID",
                "type": "string",
                "optional": True,
                "description": "Optional reference for your bridge/location; the device topic is configured when adding the alarm panel.",
            },
        ],
        "auth_type": "credentials",
    },
}
