# Generated by Django 5.2.4 on 2025-08-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_device_ip_address_device_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
