from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0006_floorplan_editor")]

    operations = [
        migrations.AlterField(
            model_name="floorplanobject",
            name="object_type",
            field=models.CharField(
                max_length=30,
                choices=[
                    ("wall", "Wall"),
                    ("door", "Door"),
                    ("window", "Window"),
                    ("stairs", "Stairs"),
                    ("column", "Column"),
                    ("radiator", "Radiator"),
                    ("fireplace", "Fireplace"),
                    ("boiler", "Boiler"),
                    ("kitchen_counter", "Kitchen counter"),
                    ("kitchen_island", "Kitchen island"),
                    ("sink", "Sink"),
                    ("oven", "Oven"),
                    ("hob", "Hob"),
                    ("fridge", "Fridge"),
                    ("freezer", "Freezer"),
                    ("dishwasher", "Dishwasher"),
                    ("washing_machine", "Washing machine"),
                    ("dryer", "Tumble dryer"),
                    ("microwave", "Microwave"),
                    ("toilet", "Toilet"),
                    ("bath", "Bath"),
                    ("shower", "Shower"),
                    ("vanity", "Bathroom vanity"),
                    ("bed", "Bed"),
                    ("wardrobe", "Wardrobe"),
                    ("chest_drawers", "Chest of drawers"),
                    ("bedside_table", "Bedside table"),
                    ("dresser", "Dresser"),
                    ("sofa", "Sofa"),
                    ("armchair", "Armchair"),
                    ("coffee_table", "Coffee table"),
                    ("side_table", "Side table"),
                    ("dining_table", "Dining table"),
                    ("dining_chair", "Dining chair"),
                    ("desk", "Desk"),
                    ("office_chair", "Office chair"),
                    ("bookshelf", "Bookshelf"),
                    ("cabinet", "Cabinet"),
                    ("storage_unit", "Storage unit"),
                    ("rug", "Rug"),
                    ("plant", "Plant"),
                    ("lamp", "Lamp"),
                    ("tv_stand", "TV stand"),
                    ("patio_table", "Patio table"),
                    ("garden_chair", "Garden chair"),
                    ("barbecue", "Barbecue"),
                    ("appliance", "Appliance"),
                    ("device", "Device"),
                    ("label", "Label"),
                ],
            ),
        ),
    ]
