import{useMemo,useState}from"react";import type{ControlDescriptor,Device}from"../types";
function optionsFor(c:ControlDescriptor,d:Device){if(c.options?.length)return c.options;if(c.options_from_state){const value=d.state?.[c.options_from_state];if(Array.isArray(value))return value.map((x:any)=>typeof x==="string"?{value:x,label:x}:x)}return[]}
export default function ControlPanel({device,controls,onControl,compact=false}:{device:Device;controls?:ControlDescriptor[];onControl:(action:string,parameters?:Record<string,any>)=>Promise<any>;compact?:boolean}){const available=controls||device.capabilities?.controls||[];const groups=useMemo(()=>available.reduce<Record<string,ControlDescriptor[]>>((a,c)=>{(a[c.group||"main"]||=[]).push(c);return a},{}),[available]);return <div className="space-y-4">{Object.entries(groups).map(([group,items])=><div key={group}>{!compact&&<div className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">{group}</div>}<div className="flex flex-wrap gap-2">{items.map(c=><One key={c.action} control={c} device={device} onControl={onControl} compact={compact}/>)}</div></div>)}{!available.length&&<div className="text-sm text-zinc-500">This device exposes status only.</div>}</div>}
function One({control,device,onControl,compact}:{control:ControlDescriptor;device:Device;onControl:(a:string,p?:Record<string,any>)=>Promise<any>;compact:boolean}){const[value,setValue]=useState<any>(device.state?.[control.parameter||control.action]??control.min??"");const[temp,setTemp]=useState(22);const[busy,setBusy]=useState(false);const invoke=async(p?:Record<string,any>)=>{setBusy(true);try{await onControl(control.action,p)}finally{setBusy(false)}};const cls="rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2 text-sm text-zinc-100 transition hover:border-cyan-500 disabled:opacity-50";
if(control.type==="range")return <label className={`${compact?"w-36":"w-56"} rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2 text-xs text-zinc-300`}><span className="flex justify-between"><span>{control.label}</span><span>{value}</span></span><input className="mt-1 w-full accent-cyan-500" type="range" min={control.min??0} max={control.max??100} step={control.step??1} value={value} onChange={e=>setValue(Number(e.target.value))} onMouseUp={()=>invoke({[control.parameter||"value"]:value})}/></label>;
if(control.type==="toggle"){const current=device.state?.[control.parameter||control.action];const enabled=current===true||current===1||["on","true"].includes(String(current).toLowerCase());return <button disabled={busy} className={cls} onClick={()=>invoke({[control.parameter||"value"]:!enabled})}>{control.label}</button>}
if(control.type==="select")return <select className={cls} defaultValue="" onChange={e=>e.target.value&&invoke({[control.parameter||"value"]:e.target.value})}><option value="">{control.label}</option>{optionsFor(control,device).map((o:any)=><option key={o.value} value={o.value}>{o.label??o.value}</option>)}</select>;
if(control.type==="text"||control.type==="media_search")return <form className="flex min-w-64 flex-1 gap-2" onSubmit={e=>{e.preventDefault();invoke({[control.parameter||"value"]:value})}}><input className="min-w-0 flex-1 rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm" value={value} onChange={e=>setValue(e.target.value)} placeholder={control.placeholder||control.label}/><button disabled={busy||!value} className={cls}>{control.type==="media_search"?"Play":"Send"}</button></form>;
if(control.type==="number_pair")return <div className="flex flex-wrap items-end gap-2"><label className="text-xs text-zinc-400">Minutes<input className="mt-1 block w-24 rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-2 text-sm" type="number" min="1" value={value||30} onChange={e=>setValue(Number(e.target.value))}/></label><label className="text-xs text-zinc-400">Temperature °C<input className="mt-1 block w-28 rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-2 text-sm" type="number" min="5" max="35" step="0.5" value={temp} onChange={e=>setTemp(Number(e.target.value))}/></label><button className={cls} disabled={busy} onClick={()=>invoke({minutes:Number(value||30),temperature:temp})}>{control.label}</button></div>;
return <button disabled={busy} className={cls} onClick={()=>invoke()}>{busy?"Working…":control.label}</button>}
