# Generated by Django 5.2.4 on 2025-08-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='config_schema',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='device',
            name='credentials',
        ),
        migrations.AddField(
            model_name='device',
            name='static_ip',
            field=models.BooleanField(default=False, help_text='Is the device using a static IP address?'),
        ),
    ]
